env: "development"
cadence:
  domain: "samples-domain"
  service: "cadence-frontend"
  hostPort: "127.0.0.1:7933"
kafka:
  clusters:
    dev:
      brokers:
        - 127.0.0.1:9092
  topics:
    wallet-dev:
      cluster: dev
  applications:
    update-wallet:
      topic: wallet-dev
      dlq-topic: wallet-dev-dlq
      