// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dense.proto

package dense

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImageData struct {
	PostId               string   `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageData) Reset()         { *m = ImageData{} }
func (m *ImageData) String() string { return proto.CompactTextString(m) }
func (*ImageData) ProtoMessage()    {}
func (*ImageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ffe1c9366ce3a3c, []int{0}
}

func (m *ImageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageData.Unmarshal(m, b)
}
func (m *ImageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageData.Marshal(b, m, deterministic)
}
func (m *ImageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageData.Merge(m, src)
}
func (m *ImageData) XXX_Size() int {
	return xxx_messageInfo_ImageData.Size(m)
}
func (m *ImageData) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageData.DiscardUnknown(m)
}

var xxx_messageInfo_ImageData proto.InternalMessageInfo

func (m *ImageData) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	IsNext               bool     `protobuf:"varint,3,opt,name=isNext,proto3" json:"isNext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ffe1c9366ce3a3c, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetIsNext() bool {
	if m != nil {
		return m.IsNext
	}
	return false
}

func init() {
	proto.RegisterType((*ImageData)(nil), "dense.ImageData")
	proto.RegisterType((*Response)(nil), "dense.Response")
}

func init() { proto.RegisterFile("dense.proto", fileDescriptor_1ffe1c9366ce3a3c) }

var fileDescriptor_1ffe1c9366ce3a3c = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x49, 0xcd, 0x2b,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x94, 0xb9, 0x38, 0x3d,
	0x73, 0x13, 0xd3, 0x53, 0x5d, 0x12, 0x4b, 0x12, 0x85, 0xc4, 0xb8, 0xd8, 0x0a, 0xf2, 0x8b, 0x4b,
	0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0xa5, 0x20, 0x2e, 0x8e, 0xa0,
	0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4,
	0xf4, 0x54, 0xa8, 0x22, 0x18, 0x57, 0x48, 0x84, 0x8b, 0x35, 0xb5, 0xa8, 0x28, 0xbf, 0x48, 0x82,
	0x09, 0x2c, 0x0e, 0xe1, 0x80, 0xcc, 0xcc, 0x2c, 0xf6, 0x4b, 0xad, 0x28, 0x91, 0x60, 0x56, 0x60,
	0xd4, 0xe0, 0x08, 0x82, 0xf2, 0x8c, 0xd6, 0x30, 0x72, 0xb1, 0x07, 0x14, 0xa5, 0xa6, 0x64, 0x26,
	0x97, 0x08, 0x19, 0x73, 0xf1, 0x14, 0x40, 0x98, 0xf1, 0x79, 0xc5, 0x69, 0xe5, 0x42, 0x02, 0x7a,
	0x10, 0x97, 0xc2, 0x5d, 0x26, 0xc5, 0x0f, 0x15, 0x81, 0x39, 0x43, 0x89, 0x01, 0x59, 0x53, 0x4e,
	0x7e, 0x7a, 0x3e, 0x71, 0x9a, 0xcc, 0xb9, 0x04, 0x60, 0x9a, 0x0a, 0x32, 0x0b, 0x52, 0x73, 0x32,
	0xf3, 0x52, 0x89, 0xd2, 0x98, 0xc4, 0x06, 0x0e, 0x35, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x49, 0xea, 0x95, 0x8b, 0x44, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PredictClient is the client API for Predict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PredictClient interface {
	PredictNsfw(ctx context.Context, in *ImageData, opts ...grpc.CallOption) (*Response, error)
	PredictLogo(ctx context.Context, in *ImageData, opts ...grpc.CallOption) (*Response, error)
	PredictPipeline(ctx context.Context, in *ImageData, opts ...grpc.CallOption) (*Response, error)
}

type predictClient struct {
	cc *grpc.ClientConn
}

func NewPredictClient(cc *grpc.ClientConn) PredictClient {
	return &predictClient{cc}
}

func (c *predictClient) PredictNsfw(ctx context.Context, in *ImageData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dense.Predict/predict_nsfw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictClient) PredictLogo(ctx context.Context, in *ImageData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dense.Predict/predict_logo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictClient) PredictPipeline(ctx context.Context, in *ImageData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dense.Predict/predict_pipeline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictServer is the server API for Predict service.
type PredictServer interface {
	PredictNsfw(context.Context, *ImageData) (*Response, error)
	PredictLogo(context.Context, *ImageData) (*Response, error)
	PredictPipeline(context.Context, *ImageData) (*Response, error)
}

// UnimplementedPredictServer can be embedded to have forward compatible implementations.
type UnimplementedPredictServer struct {
}

func (*UnimplementedPredictServer) PredictNsfw(ctx context.Context, req *ImageData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictNsfw not implemented")
}
func (*UnimplementedPredictServer) PredictLogo(ctx context.Context, req *ImageData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictLogo not implemented")
}
func (*UnimplementedPredictServer) PredictPipeline(ctx context.Context, req *ImageData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictPipeline not implemented")
}

func RegisterPredictServer(s *grpc.Server, srv PredictServer) {
	s.RegisterService(&_Predict_serviceDesc, srv)
}

func _Predict_PredictNsfw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).PredictNsfw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dense.Predict/PredictNsfw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).PredictNsfw(ctx, req.(*ImageData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Predict_PredictLogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).PredictLogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dense.Predict/PredictLogo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).PredictLogo(ctx, req.(*ImageData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Predict_PredictPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).PredictPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dense.Predict/PredictPipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).PredictPipeline(ctx, req.(*ImageData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Predict_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dense.Predict",
	HandlerType: (*PredictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "predict_nsfw",
			Handler:    _Predict_PredictNsfw_Handler,
		},
		{
			MethodName: "predict_logo",
			Handler:    _Predict_PredictLogo_Handler,
		},
		{
			MethodName: "predict_pipeline",
			Handler:    _Predict_PredictPipeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dense.proto",
}
